#!/usr/bin/env python

#-----------------------------------------------------------------------
# keys.py
#-----------------------------------------------------------------------
import os
# This file defines a key that should be kept secret. So don't place
# it in your GitHub repository -- just in case your GitHub repository
# accidentally becomes public.

# Generated by os.urandom(16)
APP_SECRET_KEY = os.urandom(16)
